// ETTEpsonPrinterActiveX.idl : ActiveX 控件项目的类型库源。

// 此文件将由 MIDL 编译器工具处理以
// 产生类型库(ETTEpsonPrinterActiveX.tlb)，该类型库将成为
// ETTEpsonPrinterActiveX.ocx.

#include <olectl.h>
#include <idispids.h>

[ uuid(67A95709-A323-46F2-9C64-72AABCD7593F), version(1.0),
  helpfile("ETTEpsonPrinterActiveX.hlp"),
  helpstring("ETTEpsonPrinterActiveX ActiveX 控件模块"),
  control ]
library ETTEpsonPrinterActiveXLib
{
	importlib(STDOLE_TLB);

	//  CETTEpsonPrinterActiveXCtrl 的主调度接口

	[ uuid(0B6C5706-C674-4856-A342-845A5E1FE55A),
	  helpstring("ETTEpsonPrinterActiveX Control 的调度接口")]
	dispinterface _DETTEpsonPrinterActiveX
	{
		properties:
			[id(6) , helpstring("属性 PrinterName")] BSTR PrinterName;
			[id(8) , helpstring("属性 Port")] SHORT Port;
	methods:
			[id(1), helpstring("方法LoadDll")] SHORT LoadDll(void);
			[id(2), helpstring("方法DestroyDll")] SHORT DestroyDll(void);
			[id(3), helpstring("方法AddString")] void AddString(void);
			[id(4), helpstring("方法RemoveAllString")] void RemoveAllString(void);
			[id(5), helpstring("方法TestMethod")] void TestMethod(void);
			[id(7), helpstring("方法PrinterPort")] SHORT PrinterPort(void);
	};

	//  CETTEpsonPrinterActiveXCtrl 的事件调度接口

	[ uuid(7BD881A4-9BCF-4F89-8BCF-095D160F2801),
	  helpstring("ETTEpsonPrinterActiveX Control 的事件接口") ]
	dispinterface _DETTEpsonPrinterActiveXEvents
	{
		properties:
			//  事件接口没有任何属性

		methods:
	};

	//  CETTEpsonPrinterActiveXCtrl 的类信息

	[ uuid(55F3EC13-28AB-469E-98DE-82E862703FC0),
	  helpstring("ETTEpsonPrinterActiveX Control"), control ]
	coclass ETTEpsonPrinterActiveX
	{
		[default] dispinterface _DETTEpsonPrinterActiveX;
		[default, source] dispinterface _DETTEpsonPrinterActiveXEvents;
	};

};
