// ETTTTReaderActiveX.idl : ActiveX 控件项目的类型库源。

// 此文件将由 MIDL 编译器工具处理以
// 产生类型库(ETTTTReaderActiveX.tlb)，该类型库将成为
// ETTTTReaderActiveX.ocx.

#include <olectl.h>
#include <idispids.h>

[ uuid(4FCC45AD-FA58-4530-BDAD-924AE9B99ADE), version(1.0),
  helpfile("ETTTTReaderActiveX.hlp"),
  helpstring("ETTTTReaderActiveX ActiveX 控件模块"),
  control ]
library ETTTTReaderActiveXLib
{
	importlib(STDOLE_TLB);

	//  CETTTTReaderActiveXCtrl 的主调度接口

	[ uuid(1E9465C2-56F8-444B-8077-783C426147B7),
	  helpstring("ETTTTReaderActiveX Control 的调度接口")]
	dispinterface _DETTTTReaderActiveX
	{
		properties:
			[id(1) , helpstring("属性 Message")] BSTR Message;
			[id(12) , helpstring("属性 Track1")] BSTR Track1;
			[id(14) , helpstring("属性 Track3")] BSTR Track3;
			[id(15) , helpstring("属性 Track2")] BSTR Track2;
	methods:
		[id(2), helpstring("方法LoadDll")] SHORT LoadDll(void);
		[id(3), helpstring("方法DestroyDll")] SHORT DestroyDll(void);
		[id(4), helpstring("方法DisableEntryEx")] SHORT DisableEntryEx(void);
		[id(5), helpstring("方法CaptureCardEx")] SHORT CaptureCardEx(void);
		[id(6), helpstring("方法OpenDeviceEx")] SHORT OpenDeviceEx(SHORT port);
		[id(7), helpstring("方法CloseDeviceEx")] SHORT CloseDeviceEx(void);
		[id(8), helpstring("方法EjectCardEx")] SHORT EjectCardEx(void);
		[id(9), helpstring("方法EnableEntryEx")] SHORT EnableEntryEx(void);
		[id(10), helpstring("方法GetDeviceStatusEx")] SHORT GetDeviceStatusEx(void);
		[id(11), helpstring("方法ReadTracksEx")] SHORT ReadTracksEx(void);
	};

	//  CETTTTReaderActiveXCtrl 的事件调度接口

	[ uuid(865397F5-6B68-4F40-9FE6-CDB5F06DB515),
	  helpstring("ETTTTReaderActiveX Control 的事件接口") ]
	dispinterface _DETTTTReaderActiveXEvents
	{
		properties:
			//  事件接口没有任何属性

		methods:
	};

	//  CETTTTReaderActiveXCtrl 的类信息

	[ uuid(959B27CC-94E2-416E-9635-C71B76B0A13E),
	  helpstring("ETTTTReaderActiveX Control"), control ]
	coclass ETTTTReaderActiveX
	{
		[default] dispinterface _DETTTTReaderActiveX;
		[default, source] dispinterface _DETTTTReaderActiveXEvents;
	};

};
