//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3615
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FingerCollection.Resource {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource2 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource2() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FingerCollection.Resource.Resource2", typeof(Resource2).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Authen Password: 的本地化字符串。
        /// </summary>
        internal static string IDE_AUTHEN_PASS {
            get {
                return ResourceManager.GetString("IDE_AUTHEN_PASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Authen Name: 的本地化字符串。
        /// </summary>
        internal static string IDE_AUTHEN_USER_NAME {
            get {
                return ResourceManager.GetString("IDE_AUTHEN_USER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DeleteUser 的本地化字符串。
        /// </summary>
        internal static string IDE_BTN_DELETE_USER {
            get {
                return ResourceManager.GetString("IDE_BTN_DELETE_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        internal static string IDE_BTN_EXIT {
            get {
                return ResourceManager.GetString("IDE_BTN_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FPUserIdentify 的本地化字符串。
        /// </summary>
        internal static string IDE_BTN_FPUSER_IDENTIFY {
            get {
                return ResourceManager.GetString("IDE_BTN_FPUSER_IDENTIFY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FPUserVerify 的本地化字符串。
        /// </summary>
        internal static string IDE_BTN_FPUSER_VERIFY {
            get {
                return ResourceManager.GetString("IDE_BTN_FPUSER_VERIFY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enroll 的本地化字符串。
        /// </summary>
        internal static string IDE_BTN_NEW_ENROLL {
            get {
                return ResourceManager.GetString("IDE_BTN_NEW_ENROLL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DisapproveUpdateFP 的本地化字符串。
        /// </summary>
        internal static string IDE_DISAP_UPDATE_FP {
            get {
                return ResourceManager.GetString("IDE_DISAP_UPDATE_FP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fingerprint type: 的本地化字符串。
        /// </summary>
        internal static string IDE_FINGERPRINT_TYPE {
            get {
                return ResourceManager.GetString("IDE_FINGERPRINT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        internal static string IDE_GRP_DELETE {
            get {
                return ResourceManager.GetString("IDE_GRP_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Identify 的本地化字符串。
        /// </summary>
        internal static string IDE_GRP_IDENTIFY {
            get {
                return ResourceManager.GetString("IDE_GRP_IDENTIFY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Register 的本地化字符串。
        /// </summary>
        internal static string IDE_GRP_REGISTER {
            get {
                return ResourceManager.GetString("IDE_GRP_REGISTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Verify 的本地化字符串。
        /// </summary>
        internal static string IDE_GRP_VERIFY {
            get {
                return ResourceManager.GetString("IDE_GRP_VERIFY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Host Name: 的本地化字符串。
        /// </summary>
        internal static string IDE_HOST_NAME {
            get {
                return ResourceManager.GetString("IDE_HOST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use INI file  set default parameters 的本地化字符串。
        /// </summary>
        internal static string IDE_INI_FILE_TEXT {
            get {
                return ResourceManager.GetString("IDE_INI_FILE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DeleteUser 的本地化字符串。
        /// </summary>
        internal static string IDE_LBL_DELETE_USER {
            get {
                return ResourceManager.GetString("IDE_LBL_DELETE_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RegUser 的本地化字符串。
        /// </summary>
        internal static string IDE_LBL_REGUSER {
            get {
                return ResourceManager.GetString("IDE_LBL_REGUSER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VerifyUser 的本地化字符串。
        /// </summary>
        internal static string IDE_LBL_VERIFY_USER {
            get {
                return ResourceManager.GetString("IDE_LBL_VERIFY_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ProductID: 的本地化字符串。
        /// </summary>
        internal static string IDE_PRODUCT_ID {
            get {
                return ResourceManager.GetString("IDE_PRODUCT_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set system parameters 的本地化字符串。
        /// </summary>
        internal static string IDE_SET_SYS_PARAS {
            get {
                return ResourceManager.GetString("IDE_SET_SYS_PARAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TrustLink Sample Code 的本地化字符串。
        /// </summary>
        internal static string IDE_TITLE {
            get {
                return ResourceManager.GetString("IDE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use Port: 的本地化字符串。
        /// </summary>
        internal static string IDE_USE_PORT {
            get {
                return ResourceManager.GetString("IDE_USE_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete User success. 的本地化字符串。
        /// </summary>
        internal static string IDS_DELETE_SUCCESS {
            get {
                return ResourceManager.GetString("IDS_DELETE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Register success. 的本地化字符串。
        /// </summary>
        internal static string IDS_ENROLL_SUCCESS {
            get {
                return ResourceManager.GetString("IDS_ENROLL_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Identify Fingerprint is success. 的本地化字符串。
        /// </summary>
        internal static string IDS_IDENTIFY_SUCCESS {
            get {
                return ResourceManager.GetString("IDS_IDENTIFY_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Return result code: 的本地化字符串。
        /// </summary>
        internal static string IDS_RESULT_CODE {
            get {
                return ResourceManager.GetString("IDS_RESULT_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Verify Fingerprint is success. 的本地化字符串。
        /// </summary>
        internal static string IDS_VERIFY_SUCCESS {
            get {
                return ResourceManager.GetString("IDS_VERIFY_SUCCESS", resourceCulture);
            }
        }
    }
}
