//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3615
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FingerCollection.Resource {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FingerCollection.Resource.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 1. Please try again to register fingerprint. 的本地化字符串。
        /// </summary>
        internal static string IDS_ADD_ENROLL_FINGERS_AGAIN {
            get {
                return ResourceManager.GetString("IDS_ADD_ENROLL_FINGERS_AGAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2.Try again to register user and fingerprint. 的本地化字符串。
        /// </summary>
        internal static string IDS_ADD_USER_AGAIN {
            get {
                return ResourceManager.GetString("IDS_ADD_USER_AGAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Register user failure. 的本地化字符串。
        /// </summary>
        internal static string IDS_ADD_USER_FAILED {
            get {
                return ResourceManager.GetString("IDS_ADD_USER_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2. Please check OS system directory the TrustLink XSDevelopment dlls is exist or not.  的本地化字符串。
        /// </summary>
        internal static string IDS_CHECK_DLL_EXISTED {
            get {
                return ResourceManager.GetString("IDS_CHECK_DLL_EXISTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 4.Check TrustLink XServer Port 的本地化字符串。
        /// </summary>
        internal static string IDS_CHECK_PORT_NUMBER {
            get {
                return ResourceManager.GetString("IDS_CHECK_PORT_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3.Check TrustLink ProductID 的本地化字符串。
        /// </summary>
        internal static string IDS_CHECK_PRODUCT_ID {
            get {
                return ResourceManager.GetString("IDS_CHECK_PRODUCT_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1.Please check the user is exist or not. 的本地化字符串。
        /// </summary>
        internal static string IDS_CHECK_USER_EXIST {
            get {
                return ResourceManager.GetString("IDS_CHECK_USER_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1.Check the user is exist or not. 的本地化字符串。
        /// </summary>
        internal static string IDS_CHECK_USER_ID {
            get {
                return ResourceManager.GetString("IDS_CHECK_USER_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1.Please contact vendor. 的本地化字符串。
        /// </summary>
        internal static string IDS_CONTACT_VENDOR {
            get {
                return ResourceManager.GetString("IDS_CONTACT_VENDOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1.Delete the exist user. 的本地化字符串。
        /// </summary>
        internal static string IDS_DELETE_EXISTED_USER_ID {
            get {
                return ResourceManager.GetString("IDS_DELETE_EXISTED_USER_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete user failure. 的本地化字符串。
        /// </summary>
        internal static string IDS_DELETE_USER_FAILED {
            get {
                return ResourceManager.GetString("IDS_DELETE_USER_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enroll fingerprint failure. 的本地化字符串。
        /// </summary>
        internal static string IDS_ENROLL_FINGERS_FAILED {
            get {
                return ResourceManager.GetString("IDS_ENROLL_FINGERS_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Authen Error 的本地化字符串。
        /// </summary>
        internal static string IDS_FPAUTHEN_ERROR {
            get {
                return ResourceManager.GetString("IDS_FPAUTHEN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Identify Error 的本地化字符串。
        /// </summary>
        internal static string IDS_FPIDENT_ERROR {
            get {
                return ResourceManager.GetString("IDS_FPIDENT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get Enrolled Finger error. 的本地化字符串。
        /// </summary>
        internal static string IDS_GET_ENROLL_FINGER_ERROR {
            get {
                return ResourceManager.GetString("IDS_GET_ENROLL_FINGER_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2.Check the user already registered fingerprint. 的本地化字符串。
        /// </summary>
        internal static string IDS_IS_USER_FINGER_EXIST {
            get {
                return ResourceManager.GetString("IDS_IS_USER_FINGER_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load TrustLink XSDevelopment dlls failure. 的本地化字符串。
        /// </summary>
        internal static string IDS_LOAD_DLL_FAILED {
            get {
                return ResourceManager.GetString("IDS_LOAD_DLL_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1. Lose TrustLink XSDevelopment dlls. 的本地化字符串。
        /// </summary>
        internal static string IDS_MISSING_DLL {
            get {
                return ResourceManager.GetString("IDS_MISSING_DLL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Proposal :  的本地化字符串。
        /// </summary>
        internal static string IDS_SUGGEST_ITEM {
            get {
                return ResourceManager.GetString("IDS_SUGGEST_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknow error 的本地化字符串。
        /// </summary>
        internal static string IDS_UNKNOW_ERROR {
            get {
                return ResourceManager.GetString("IDS_UNKNOW_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1.Please verify user fingerprint again. 的本地化字符串。
        /// </summary>
        internal static string IDS_USE_VALID_ENROLL_FINGERS_AGAIN {
            get {
                return ResourceManager.GetString("IDS_USE_VALID_ENROLL_FINGERS_AGAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TrustLink XServer Connect failure. 的本地化字符串。
        /// </summary>
        internal static string IDS_XSERVER_CONNECT_FAILED {
            get {
                return ResourceManager.GetString("IDS_XSERVER_CONNECT_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2. restart XServer. 的本地化字符串。
        /// </summary>
        internal static string IDS_XSERVER_RESTART {
            get {
                return ResourceManager.GetString("IDS_XSERVER_RESTART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1.Check TrustLink XServer is start or stop. 的本地化字符串。
        /// </summary>
        internal static string IDS_XSERVER_SHUT_DOWN {
            get {
                return ResourceManager.GetString("IDS_XSERVER_SHUT_DOWN", resourceCulture);
            }
        }
    }
}
