drop table myusers;
drop table mydicts;
drop table receiverecord;
drop table receivedetail;
drop table yiku;
drop table zutuo;
drop table jietuo;
drop table pintuo;
drop table sendrecord;
drop table senddetail;
drop table pandianrecord;
drop table pandiandetail;
drop table kuweiinfo