// ATLActivex.idl : ATLActivex 的 IDL 源
//

// 此文件将由 MIDL 工具处理以
// 产生类型库(ATLActivex.tlb)和封送处理代码。

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(9C0C7658-88BC-4200-B39E-1E8BE7F27744),
	version(1.0),
	helpstring("ATLActivex 1.0 类型库")
]
library ATLActivexLib
{
	importlib("stdole2.tlb");
};
