//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3615
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 2.0.50727.3615 版自动生成。
// 
#pragma warning disable 1591

namespace FT.Windows.ExternalTool.localhost {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DrvSoapBinding", Namespace="http://wsdl.Drv")]
    public partial class DrvService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getDrvimageOperationCompleted;
        
        private System.Threading.SendOrPostCallback write_drvimageOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DrvService() {
            this.Url = global::FT.Windows.ExternalTool.Properties.Settings.Default.FT_Windows_ExternalTool_localhost_DrvService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getDrvimageCompletedEventHandler getDrvimageCompleted;
        
        /// <remarks/>
        public event write_drvimageCompletedEventHandler write_drvimageCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://wsdl.Drv", ResponseNamespace="http://wsdl.Drv", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("getDrvimageReturn")]
        public string getDrvimage(string sfzmmc, string sfzmhm, string sn) {
            object[] results = this.Invoke("getDrvimage", new object[] {
                        sfzmmc,
                        sfzmhm,
                        sn});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getDrvimageAsync(string sfzmmc, string sfzmhm, string sn) {
            this.getDrvimageAsync(sfzmmc, sfzmhm, sn, null);
        }
        
        /// <remarks/>
        public void getDrvimageAsync(string sfzmmc, string sfzmhm, string sn, object userState) {
            if ((this.getDrvimageOperationCompleted == null)) {
                this.getDrvimageOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetDrvimageOperationCompleted);
            }
            this.InvokeAsync("getDrvimage", new object[] {
                        sfzmmc,
                        sfzmhm,
                        sn}, this.getDrvimageOperationCompleted, userState);
        }
        
        private void OngetDrvimageOperationCompleted(object arg) {
            if ((this.getDrvimageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getDrvimageCompleted(this, new getDrvimageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://wsdl.Drv", ResponseNamespace="http://wsdl.Drv", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("write_drvimageReturn")]
        public string write_drvimage(string sfzmmc, string sfzmhm, string zp, string sn) {
            object[] results = this.Invoke("write_drvimage", new object[] {
                        sfzmmc,
                        sfzmhm,
                        zp,
                        sn});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void write_drvimageAsync(string sfzmmc, string sfzmhm, string zp, string sn) {
            this.write_drvimageAsync(sfzmmc, sfzmhm, zp, sn, null);
        }
        
        /// <remarks/>
        public void write_drvimageAsync(string sfzmmc, string sfzmhm, string zp, string sn, object userState) {
            if ((this.write_drvimageOperationCompleted == null)) {
                this.write_drvimageOperationCompleted = new System.Threading.SendOrPostCallback(this.Onwrite_drvimageOperationCompleted);
            }
            this.InvokeAsync("write_drvimage", new object[] {
                        sfzmmc,
                        sfzmhm,
                        zp,
                        sn}, this.write_drvimageOperationCompleted, userState);
        }
        
        private void Onwrite_drvimageOperationCompleted(object arg) {
            if ((this.write_drvimageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.write_drvimageCompleted(this, new write_drvimageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void getDrvimageCompletedEventHandler(object sender, getDrvimageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getDrvimageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getDrvimageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void write_drvimageCompletedEventHandler(object sender, write_drvimageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class write_drvimageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal write_drvimageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591