// ETTPrinter.idl : ActiveX 控件项目的类型库源。

// 此文件将由 MIDL 编译器工具处理以
// 产生类型库(ETTPrinter.tlb)，该类型库将成为
// ETTPrinter.ocx.

#include <olectl.h>
#include <idispids.h>

[ uuid(89C1FE4C-0CCE-4F7F-A8F4-304F00407457), version(1.0),
  helpfile("ETTPrinter.hlp"),
  helpstring("ETTPrinter ActiveX 控件模块"),
  control ]
library ETTPrinterLib
{
	importlib(STDOLE_TLB);

	//  CETTPrinterCtrl 的主调度接口

	[ uuid(2F34318A-00C9-4BA3-A13B-E3C89239E815),
	  helpstring("ETTPrinter Control 的调度接口")]
	dispinterface _DETTPrinter
	{
		properties:
		methods:
	};

	//  CETTPrinterCtrl 的事件调度接口

	[ uuid(B964845C-BDE0-46E8-A5C1-071D57029D4F),
	  helpstring("ETTPrinter Control 的事件接口") ]
	dispinterface _DETTPrinterEvents
	{
		properties:
			//  事件接口没有任何属性

		methods:
	};

	//  CETTPrinterCtrl 的类信息

	[ uuid(08A5FF49-503B-4518-8016-87F4AF50D7A1),
	  helpstring("ETTPrinter Control"), control ]
	coclass ETTPrinter
	{
		[default] dispinterface _DETTPrinter;
		[default, source] dispinterface _DETTPrinterEvents;
	};

};
