// ETTSelfPrinterActiveX.idl : ActiveX 控件项目的类型库源。

// 此文件将由 MIDL 编译器工具处理以
// 产生类型库(ETTSelfPrinterActiveX.tlb)，该类型库将成为
// ETTSelfPrinterActiveX.ocx.

#include <olectl.h>
#include <idispids.h>

[ uuid(AD83D01E-7CCF-496D-BD99-121AA5BCDE85), version(1.0),
  helpfile("ETTSelfPrinterActiveX.hlp"),
  helpstring("ETTSelfPrinterActiveX ActiveX 控件模块"),
  control ]
library ETTSelfPrinterActiveXLib
{
	importlib(STDOLE_TLB);

	//  CETTSelfPrinterActiveXCtrl 的主调度接口

	[ uuid(D30B98E7-F1BB-402D-8E60-6D7FAD93F628),
	  helpstring("ETTSelfPrinterActiveX Control 的调度接口")]
	dispinterface _DETTSelfPrinterActiveX
	{
		properties:
			[id(1) , helpstring("属性 MyTestMessage")] BSTR MyTestMessage;
	methods:
		[id(2), helpstring("方法OpenDeviceEx")] SHORT OpenDeviceEx(SHORT port);
		[id(3), helpstring("方法CloseDeviceEx")] SHORT CloseDeviceEx(void);
		[id(4), helpstring("方法SetRowDistanceEx")] SHORT SetRowDistanceEx(void);
		[id(5), helpstring("方法PrintLineEx")] SHORT PrintLineEx(void);
		[id(6), helpstring("方法CutPaperEx")] SHORT CutPaperEx(void);
		[id(7), helpstring("方法PrintLineEx2")] SHORT PrintLineEx2(BSTR* data);
		[id(8), helpstring("方法ClearAll")] SHORT ClearAll(void);
		[id(9), helpstring("方法AddString")] SHORT AddString(BSTR data);
		[id(10), helpstring("方法Test")] SHORT Test(void);
		[id(11), helpstring("方法ShowArray")] void ShowArray(void);
	};

	//  CETTSelfPrinterActiveXCtrl 的事件调度接口

	[ uuid(889818F0-7383-4B13-A150-6E777278ABBC),
	  helpstring("ETTSelfPrinterActiveX Control 的事件接口") ]
	dispinterface _DETTSelfPrinterActiveXEvents
	{
		properties:
			[id(2) , helpstring("属性 GLBM")] BSTR Glbm;
			[id(3) , helpstring("属性 LSH")] BSTR Lsh;
			[id(4) , helpstring("属性 YWLX")] BSTR Ywlx;
			[id(5) , helpstring("属性 Owner")] BSTR Owner;
			[id(6) , helpstring("属性 Hmhp")] BSTR Hmhp;
			[id(7) , helpstring("属性 Slrq")] BSTR Slrq;
			[id(8) , helpstring("属性 Fee")] BSTR Fee;
			[id(9) , helpstring("属性 Hint")] BSTR Hint;
			[id(10) , helpstring("属性 Jszh")] BSTR Jszh;
			[id(11) , helpstring("属性 Ksrq")] BSTR Ksrq;
			[id(12) , helpstring("属性 Yyrq")] BSTR Yyrq;
			[id(13) , helpstring("属性 PrinterName")] BSTR PrinterName;
			//  事件接口没有任何属性

		methods:
			[id(1), helpstring("方法CarPrint")] SHORT CarPrint(void);
			[id(14), helpstring("方法LoadReceiptDll")] SHORT LoadReceiptDll(void);
			[id(15), helpstring("方法LoadInvoiceDll")] SHORT LoadInvoiceDll(void);
			[id(16), helpstring("方法DestroyDll")] SHORT DestroyDll(void);
	};

	//  CETTSelfPrinterActiveXCtrl 的类信息

	[ uuid(4F193682-5451-4CD5-8340-63DD04D2FAD9),
	  helpstring("ETTSelfPrinterActiveX Control"), control ]
	coclass ETTSelfPrinterActiveX
	{
		[default] dispinterface _DETTSelfPrinterActiveX;
		[default, source] dispinterface _DETTSelfPrinterActiveXEvents;
	};

};
