// VoiceActiveX.idl : ActiveX 控件项目的类型库源。

// 此文件将由 MIDL 编译器工具处理以
// 产生类型库(VoiceActiveX.tlb)，该类型库将成为
// VoiceActiveX.ocx.

#include <olectl.h>
#include <idispids.h>

[ uuid(66299FE8-DFC5-47AB-B225-E80DA6412935), version(1.0),
  helpfile("VoiceActiveX.hlp"),
  helpstring("VoiceActiveX ActiveX 控件模块"),
  control ]
library VoiceActiveXLib
{
	importlib(STDOLE_TLB);

	//  CVoiceActiveXCtrl 的主调度接口

	[ uuid(D1742149-26BE-4081-AA2A-0535AC92F971),
	  helpstring("VoiceActiveX Control 的调度接口")]
	dispinterface _DVoiceActiveX
	{
		properties:
		methods:
	};

	//  CVoiceActiveXCtrl 的事件调度接口

	[ uuid(4D3FD060-59E1-4CF3-9B46-9FFCFE489460),
	  helpstring("VoiceActiveX Control 的事件接口") ]
	dispinterface _DVoiceActiveXEvents
	{
		properties:
			[id(1) , helpstring("属性 FileName")] BSTR FileName;
			//  事件接口没有任何属性

		methods:
			[id(2), helpstring("方法PlayVoice"), local, source] void PlayVoice(BSTR IDR_Voice);
	};

	//  CVoiceActiveXCtrl 的类信息

	[ uuid(3BE2B9A6-A746-40AE-A54E-705EFB3C98E2),
	  helpstring("VoiceActiveX Control"), control ]
	coclass VoiceActiveX
	{
		[default] dispinterface _DVoiceActiveX;
		[default, source] dispinterface _DVoiceActiveXEvents;
	};

};
