//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.1433
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 2.0.50727.1433 版自动生成。
// 
#pragma warning disable 1591

namespace PhotoMonitor.DrvNewService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TmriOutAccessSoapBinding", Namespace="http://10.40.30.92/trffweb/services/TmriOutAccess")]
    public partial class TmriJaxRpcOutAccessService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback queryObjectOutOperationCompleted;
        
        private System.Threading.SendOrPostCallback writeObjectOutOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public TmriJaxRpcOutAccessService() {
            this.Url = global::PhotoMonitor.Properties.Settings.Default.PhotoMonitor_DrvNewService_TmriJaxRpcOutAccessService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event queryObjectOutCompletedEventHandler queryObjectOutCompleted;
        
        /// <remarks/>
        public event writeObjectOutCompletedEventHandler writeObjectOutCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://endpoint.axis.framework.tmri.com", ResponseNamespace="http://10.40.30.92/trffweb/services/TmriOutAccess")]
        [return: System.Xml.Serialization.SoapElementAttribute("queryObjectOutReturn")]
        public string queryObjectOut(string xtlb, string jkxlh, string jkid, string UTF8XmlDoc) {
            object[] results = this.Invoke("queryObjectOut", new object[] {
                        xtlb,
                        jkxlh,
                        jkid,
                        UTF8XmlDoc});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void queryObjectOutAsync(string xtlb, string jkxlh, string jkid, string UTF8XmlDoc) {
            this.queryObjectOutAsync(xtlb, jkxlh, jkid, UTF8XmlDoc, null);
        }
        
        /// <remarks/>
        public void queryObjectOutAsync(string xtlb, string jkxlh, string jkid, string UTF8XmlDoc, object userState) {
            if ((this.queryObjectOutOperationCompleted == null)) {
                this.queryObjectOutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryObjectOutOperationCompleted);
            }
            this.InvokeAsync("queryObjectOut", new object[] {
                        xtlb,
                        jkxlh,
                        jkid,
                        UTF8XmlDoc}, this.queryObjectOutOperationCompleted, userState);
        }
        
        private void OnqueryObjectOutOperationCompleted(object arg) {
            if ((this.queryObjectOutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.queryObjectOutCompleted(this, new queryObjectOutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://endpoint.axis.framework.tmri.com", ResponseNamespace="http://10.40.30.92/trffweb/services/TmriOutAccess")]
        [return: System.Xml.Serialization.SoapElementAttribute("writeObjectOutReturn")]
        public string writeObjectOut(string xtlb, string jkxlh, string jkid, string UTF8XmlDoc) {
            object[] results = this.Invoke("writeObjectOut", new object[] {
                        xtlb,
                        jkxlh,
                        jkid,
                        UTF8XmlDoc});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void writeObjectOutAsync(string xtlb, string jkxlh, string jkid, string UTF8XmlDoc) {
            this.writeObjectOutAsync(xtlb, jkxlh, jkid, UTF8XmlDoc, null);
        }
        
        /// <remarks/>
        public void writeObjectOutAsync(string xtlb, string jkxlh, string jkid, string UTF8XmlDoc, object userState) {
            if ((this.writeObjectOutOperationCompleted == null)) {
                this.writeObjectOutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnwriteObjectOutOperationCompleted);
            }
            this.InvokeAsync("writeObjectOut", new object[] {
                        xtlb,
                        jkxlh,
                        jkid,
                        UTF8XmlDoc}, this.writeObjectOutOperationCompleted, userState);
        }
        
        private void OnwriteObjectOutOperationCompleted(object arg) {
            if ((this.writeObjectOutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.writeObjectOutCompleted(this, new writeObjectOutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void queryObjectOutCompletedEventHandler(object sender, queryObjectOutCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class queryObjectOutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal queryObjectOutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void writeObjectOutCompletedEventHandler(object sender, writeObjectOutCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class writeObjectOutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal writeObjectOutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591