// MyActiveX.idl : ActiveX 控件项目的类型库源。

// 此文件将由 MIDL 编译器工具处理以
// 产生类型库(MyActiveX.tlb)，该类型库将成为
// MyActiveX.ocx.

#include <olectl.h>
#include <idispids.h>

[ uuid(A5B3C774-D499-4DBF-BC04-3D23B971430F), version(1.0),
  helpfile("MyActiveX.hlp"),
  helpstring("MyActiveX ActiveX 控件模块"),
  control ]
library MyActiveXLib
{
	importlib(STDOLE_TLB);

	//  CMyActiveXCtrl 的主调度接口

	[ uuid(8CE1671B-AA29-4130-854B-613A39A82298),
	  helpstring("MyActiveX Control 的调度接口")]
	dispinterface _DMyActiveX
	{
		properties:
			[id(2)] BSTR MessageStr;
		methods:
			[id(1)] short ShowMessageBox();
	};

	//  CMyActiveXCtrl 的事件调度接口

	[ uuid(ABCE71F8-C8D6-4B80-B24C-0073D63C1CAE),
	  helpstring("MyActiveX Control 的事件接口") ]
	dispinterface _DMyActiveXEvents
	{
		properties:
			//  事件接口没有任何属性

		methods:
	};

	//  CMyActiveXCtrl 的类信息

	[ uuid(3978BB54-FC56-4784-9A6B-E880C8E71B41),
	  helpstring("MyActiveX Control"), control ]
	coclass MyActiveX
	{
		[default] dispinterface _DMyActiveX;
		[default, source] dispinterface _DMyActiveXEvents;
	};

};
