//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.1432.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="VioSoapBinding", Namespace="http://service.ws.tmri.com")]
public partial class VioService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback write_yhdzOperationCompleted;
    
    private System.Threading.SendOrPostCallback write_surveilOperationCompleted;
    
    private System.Threading.SendOrPostCallback write_violation_jyOperationCompleted;
    
    private System.Threading.SendOrPostCallback write_forceOperationCompleted;
    
    private System.Threading.SendOrPostCallback getVehViolationOperationCompleted;
    
    private System.Threading.SendOrPostCallback getDrvViolationOperationCompleted;
    
    private System.Threading.SendOrPostCallback write_mid_jdczpOperationCompleted;
    
    /// <remarks/>
    public VioService() {
        this.Url = "http://10.40.30.250:80/servweb/services/Vio";
    }
    
    /// <remarks/>
    public event write_yhdzCompletedEventHandler write_yhdzCompleted;
    
    /// <remarks/>
    public event write_surveilCompletedEventHandler write_surveilCompleted;
    
    /// <remarks/>
    public event write_violation_jyCompletedEventHandler write_violation_jyCompleted;
    
    /// <remarks/>
    public event write_forceCompletedEventHandler write_forceCompleted;
    
    /// <remarks/>
    public event getVehViolationCompletedEventHandler getVehViolationCompleted;
    
    /// <remarks/>
    public event getDrvViolationCompletedEventHandler getDrvViolationCompleted;
    
    /// <remarks/>
    public event write_mid_jdczpCompletedEventHandler write_mid_jdczpCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.ws.tmri.com", ResponseNamespace="http://service.ws.tmri.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("write_yhdzReturn", IsNullable=true)]
    public string write_yhdz([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_0_0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_1_0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_2_0, long arg_3_0, long arg_4_0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_5_0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_6_0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_7_0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_8_0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_9_0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_10_0) {
        object[] results = this.Invoke("write_yhdz", new object[] {
                    arg_0_0,
                    arg_1_0,
                    arg_2_0,
                    arg_3_0,
                    arg_4_0,
                    arg_5_0,
                    arg_6_0,
                    arg_7_0,
                    arg_8_0,
                    arg_9_0,
                    arg_10_0});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult Beginwrite_yhdz(string arg_0_0, string arg_1_0, string arg_2_0, long arg_3_0, long arg_4_0, string arg_5_0, string arg_6_0, string arg_7_0, string arg_8_0, string arg_9_0, string arg_10_0, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("write_yhdz", new object[] {
                    arg_0_0,
                    arg_1_0,
                    arg_2_0,
                    arg_3_0,
                    arg_4_0,
                    arg_5_0,
                    arg_6_0,
                    arg_7_0,
                    arg_8_0,
                    arg_9_0,
                    arg_10_0}, callback, asyncState);
    }
    
    /// <remarks/>
    public string Endwrite_yhdz(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void write_yhdzAsync(string arg_0_0, string arg_1_0, string arg_2_0, long arg_3_0, long arg_4_0, string arg_5_0, string arg_6_0, string arg_7_0, string arg_8_0, string arg_9_0, string arg_10_0) {
        this.write_yhdzAsync(arg_0_0, arg_1_0, arg_2_0, arg_3_0, arg_4_0, arg_5_0, arg_6_0, arg_7_0, arg_8_0, arg_9_0, arg_10_0, null);
    }
    
    /// <remarks/>
    public void write_yhdzAsync(string arg_0_0, string arg_1_0, string arg_2_0, long arg_3_0, long arg_4_0, string arg_5_0, string arg_6_0, string arg_7_0, string arg_8_0, string arg_9_0, string arg_10_0, object userState) {
        if ((this.write_yhdzOperationCompleted == null)) {
            this.write_yhdzOperationCompleted = new System.Threading.SendOrPostCallback(this.Onwrite_yhdzOperationCompleted);
        }
        this.InvokeAsync("write_yhdz", new object[] {
                    arg_0_0,
                    arg_1_0,
                    arg_2_0,
                    arg_3_0,
                    arg_4_0,
                    arg_5_0,
                    arg_6_0,
                    arg_7_0,
                    arg_8_0,
                    arg_9_0,
                    arg_10_0}, this.write_yhdzOperationCompleted, userState);
    }
    
    private void Onwrite_yhdzOperationCompleted(object arg) {
        if ((this.write_yhdzCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.write_yhdzCompleted(this, new write_yhdzCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.ws.tmri.com", ResponseNamespace="http://service.ws.tmri.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("write_surveilReturn", IsNullable=true)]
    public string write_surveil(
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_0_1, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_1_1, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_2_1, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_3_1, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_4_1, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_5_1, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_6_1, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_7_1, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_8_1, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_9_1, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_10_1, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_11_1, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_12_1, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_13_1, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_14_1, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_15_1, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_16_1, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_17_1, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_18_1, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_19_1, 
                long arg_20_1, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_21_1, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_22_1, 
                long arg_23_1, 
                long arg_24_1, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_25_1) {
        object[] results = this.Invoke("write_surveil", new object[] {
                    arg_0_1,
                    arg_1_1,
                    arg_2_1,
                    arg_3_1,
                    arg_4_1,
                    arg_5_1,
                    arg_6_1,
                    arg_7_1,
                    arg_8_1,
                    arg_9_1,
                    arg_10_1,
                    arg_11_1,
                    arg_12_1,
                    arg_13_1,
                    arg_14_1,
                    arg_15_1,
                    arg_16_1,
                    arg_17_1,
                    arg_18_1,
                    arg_19_1,
                    arg_20_1,
                    arg_21_1,
                    arg_22_1,
                    arg_23_1,
                    arg_24_1,
                    arg_25_1});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult Beginwrite_surveil(
                string arg_0_1, 
                string arg_1_1, 
                string arg_2_1, 
                string arg_3_1, 
                string arg_4_1, 
                string arg_5_1, 
                string arg_6_1, 
                string arg_7_1, 
                string arg_8_1, 
                string arg_9_1, 
                string arg_10_1, 
                string arg_11_1, 
                string arg_12_1, 
                string arg_13_1, 
                string arg_14_1, 
                string arg_15_1, 
                string arg_16_1, 
                string arg_17_1, 
                string arg_18_1, 
                string arg_19_1, 
                long arg_20_1, 
                string arg_21_1, 
                string arg_22_1, 
                long arg_23_1, 
                long arg_24_1, 
                string arg_25_1, 
                System.AsyncCallback callback, 
                object asyncState) {
        return this.BeginInvoke("write_surveil", new object[] {
                    arg_0_1,
                    arg_1_1,
                    arg_2_1,
                    arg_3_1,
                    arg_4_1,
                    arg_5_1,
                    arg_6_1,
                    arg_7_1,
                    arg_8_1,
                    arg_9_1,
                    arg_10_1,
                    arg_11_1,
                    arg_12_1,
                    arg_13_1,
                    arg_14_1,
                    arg_15_1,
                    arg_16_1,
                    arg_17_1,
                    arg_18_1,
                    arg_19_1,
                    arg_20_1,
                    arg_21_1,
                    arg_22_1,
                    arg_23_1,
                    arg_24_1,
                    arg_25_1}, callback, asyncState);
    }
    
    /// <remarks/>
    public string Endwrite_surveil(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void write_surveilAsync(
                string arg_0_1, 
                string arg_1_1, 
                string arg_2_1, 
                string arg_3_1, 
                string arg_4_1, 
                string arg_5_1, 
                string arg_6_1, 
                string arg_7_1, 
                string arg_8_1, 
                string arg_9_1, 
                string arg_10_1, 
                string arg_11_1, 
                string arg_12_1, 
                string arg_13_1, 
                string arg_14_1, 
                string arg_15_1, 
                string arg_16_1, 
                string arg_17_1, 
                string arg_18_1, 
                string arg_19_1, 
                long arg_20_1, 
                string arg_21_1, 
                string arg_22_1, 
                long arg_23_1, 
                long arg_24_1, 
                string arg_25_1) {
        this.write_surveilAsync(arg_0_1, arg_1_1, arg_2_1, arg_3_1, arg_4_1, arg_5_1, arg_6_1, arg_7_1, arg_8_1, arg_9_1, arg_10_1, arg_11_1, arg_12_1, arg_13_1, arg_14_1, arg_15_1, arg_16_1, arg_17_1, arg_18_1, arg_19_1, arg_20_1, arg_21_1, arg_22_1, arg_23_1, arg_24_1, arg_25_1, null);
    }
    
    /// <remarks/>
    public void write_surveilAsync(
                string arg_0_1, 
                string arg_1_1, 
                string arg_2_1, 
                string arg_3_1, 
                string arg_4_1, 
                string arg_5_1, 
                string arg_6_1, 
                string arg_7_1, 
                string arg_8_1, 
                string arg_9_1, 
                string arg_10_1, 
                string arg_11_1, 
                string arg_12_1, 
                string arg_13_1, 
                string arg_14_1, 
                string arg_15_1, 
                string arg_16_1, 
                string arg_17_1, 
                string arg_18_1, 
                string arg_19_1, 
                long arg_20_1, 
                string arg_21_1, 
                string arg_22_1, 
                long arg_23_1, 
                long arg_24_1, 
                string arg_25_1, 
                object userState) {
        if ((this.write_surveilOperationCompleted == null)) {
            this.write_surveilOperationCompleted = new System.Threading.SendOrPostCallback(this.Onwrite_surveilOperationCompleted);
        }
        this.InvokeAsync("write_surveil", new object[] {
                    arg_0_1,
                    arg_1_1,
                    arg_2_1,
                    arg_3_1,
                    arg_4_1,
                    arg_5_1,
                    arg_6_1,
                    arg_7_1,
                    arg_8_1,
                    arg_9_1,
                    arg_10_1,
                    arg_11_1,
                    arg_12_1,
                    arg_13_1,
                    arg_14_1,
                    arg_15_1,
                    arg_16_1,
                    arg_17_1,
                    arg_18_1,
                    arg_19_1,
                    arg_20_1,
                    arg_21_1,
                    arg_22_1,
                    arg_23_1,
                    arg_24_1,
                    arg_25_1}, this.write_surveilOperationCompleted, userState);
    }
    
    private void Onwrite_surveilOperationCompleted(object arg) {
        if ((this.write_surveilCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.write_surveilCompleted(this, new write_surveilCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.ws.tmri.com", ResponseNamespace="http://service.ws.tmri.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("write_violation_jyReturn", IsNullable=true)]
    public string write_violation_jy(
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_0_2, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_1_2, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_2_2, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_3_2, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_4_2, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_5_2, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_6_2, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_7_2, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_8_2, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_9_2, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_10_2, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_11_2, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_12_2, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_13_2, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_14_2, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_15_2, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_16_2, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_17_2, 
                long arg_18_2, 
                long arg_19_2, 
                long arg_20_2, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_21_2, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_22_2, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_23_2, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_24_2, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_25_2, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_26_2, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_27_2, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_28_2, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_29_2, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_30_2, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_31_2, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_32_2, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_33_2, 
                long arg_34_2, 
                long arg_35_2, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_36_2) {
        object[] results = this.Invoke("write_violation_jy", new object[] {
                    arg_0_2,
                    arg_1_2,
                    arg_2_2,
                    arg_3_2,
                    arg_4_2,
                    arg_5_2,
                    arg_6_2,
                    arg_7_2,
                    arg_8_2,
                    arg_9_2,
                    arg_10_2,
                    arg_11_2,
                    arg_12_2,
                    arg_13_2,
                    arg_14_2,
                    arg_15_2,
                    arg_16_2,
                    arg_17_2,
                    arg_18_2,
                    arg_19_2,
                    arg_20_2,
                    arg_21_2,
                    arg_22_2,
                    arg_23_2,
                    arg_24_2,
                    arg_25_2,
                    arg_26_2,
                    arg_27_2,
                    arg_28_2,
                    arg_29_2,
                    arg_30_2,
                    arg_31_2,
                    arg_32_2,
                    arg_33_2,
                    arg_34_2,
                    arg_35_2,
                    arg_36_2});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult Beginwrite_violation_jy(
                string arg_0_2, 
                string arg_1_2, 
                string arg_2_2, 
                string arg_3_2, 
                string arg_4_2, 
                string arg_5_2, 
                string arg_6_2, 
                string arg_7_2, 
                string arg_8_2, 
                string arg_9_2, 
                string arg_10_2, 
                string arg_11_2, 
                string arg_12_2, 
                string arg_13_2, 
                string arg_14_2, 
                string arg_15_2, 
                string arg_16_2, 
                string arg_17_2, 
                long arg_18_2, 
                long arg_19_2, 
                long arg_20_2, 
                string arg_21_2, 
                string arg_22_2, 
                string arg_23_2, 
                string arg_24_2, 
                string arg_25_2, 
                string arg_26_2, 
                string arg_27_2, 
                string arg_28_2, 
                string arg_29_2, 
                string arg_30_2, 
                string arg_31_2, 
                string arg_32_2, 
                string arg_33_2, 
                long arg_34_2, 
                long arg_35_2, 
                string arg_36_2, 
                System.AsyncCallback callback, 
                object asyncState) {
        return this.BeginInvoke("write_violation_jy", new object[] {
                    arg_0_2,
                    arg_1_2,
                    arg_2_2,
                    arg_3_2,
                    arg_4_2,
                    arg_5_2,
                    arg_6_2,
                    arg_7_2,
                    arg_8_2,
                    arg_9_2,
                    arg_10_2,
                    arg_11_2,
                    arg_12_2,
                    arg_13_2,
                    arg_14_2,
                    arg_15_2,
                    arg_16_2,
                    arg_17_2,
                    arg_18_2,
                    arg_19_2,
                    arg_20_2,
                    arg_21_2,
                    arg_22_2,
                    arg_23_2,
                    arg_24_2,
                    arg_25_2,
                    arg_26_2,
                    arg_27_2,
                    arg_28_2,
                    arg_29_2,
                    arg_30_2,
                    arg_31_2,
                    arg_32_2,
                    arg_33_2,
                    arg_34_2,
                    arg_35_2,
                    arg_36_2}, callback, asyncState);
    }
    
    /// <remarks/>
    public string Endwrite_violation_jy(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void write_violation_jyAsync(
                string arg_0_2, 
                string arg_1_2, 
                string arg_2_2, 
                string arg_3_2, 
                string arg_4_2, 
                string arg_5_2, 
                string arg_6_2, 
                string arg_7_2, 
                string arg_8_2, 
                string arg_9_2, 
                string arg_10_2, 
                string arg_11_2, 
                string arg_12_2, 
                string arg_13_2, 
                string arg_14_2, 
                string arg_15_2, 
                string arg_16_2, 
                string arg_17_2, 
                long arg_18_2, 
                long arg_19_2, 
                long arg_20_2, 
                string arg_21_2, 
                string arg_22_2, 
                string arg_23_2, 
                string arg_24_2, 
                string arg_25_2, 
                string arg_26_2, 
                string arg_27_2, 
                string arg_28_2, 
                string arg_29_2, 
                string arg_30_2, 
                string arg_31_2, 
                string arg_32_2, 
                string arg_33_2, 
                long arg_34_2, 
                long arg_35_2, 
                string arg_36_2) {
        this.write_violation_jyAsync(arg_0_2, arg_1_2, arg_2_2, arg_3_2, arg_4_2, arg_5_2, arg_6_2, arg_7_2, arg_8_2, arg_9_2, arg_10_2, arg_11_2, arg_12_2, arg_13_2, arg_14_2, arg_15_2, arg_16_2, arg_17_2, arg_18_2, arg_19_2, arg_20_2, arg_21_2, arg_22_2, arg_23_2, arg_24_2, arg_25_2, arg_26_2, arg_27_2, arg_28_2, arg_29_2, arg_30_2, arg_31_2, arg_32_2, arg_33_2, arg_34_2, arg_35_2, arg_36_2, null);
    }
    
    /// <remarks/>
    public void write_violation_jyAsync(
                string arg_0_2, 
                string arg_1_2, 
                string arg_2_2, 
                string arg_3_2, 
                string arg_4_2, 
                string arg_5_2, 
                string arg_6_2, 
                string arg_7_2, 
                string arg_8_2, 
                string arg_9_2, 
                string arg_10_2, 
                string arg_11_2, 
                string arg_12_2, 
                string arg_13_2, 
                string arg_14_2, 
                string arg_15_2, 
                string arg_16_2, 
                string arg_17_2, 
                long arg_18_2, 
                long arg_19_2, 
                long arg_20_2, 
                string arg_21_2, 
                string arg_22_2, 
                string arg_23_2, 
                string arg_24_2, 
                string arg_25_2, 
                string arg_26_2, 
                string arg_27_2, 
                string arg_28_2, 
                string arg_29_2, 
                string arg_30_2, 
                string arg_31_2, 
                string arg_32_2, 
                string arg_33_2, 
                long arg_34_2, 
                long arg_35_2, 
                string arg_36_2, 
                object userState) {
        if ((this.write_violation_jyOperationCompleted == null)) {
            this.write_violation_jyOperationCompleted = new System.Threading.SendOrPostCallback(this.Onwrite_violation_jyOperationCompleted);
        }
        this.InvokeAsync("write_violation_jy", new object[] {
                    arg_0_2,
                    arg_1_2,
                    arg_2_2,
                    arg_3_2,
                    arg_4_2,
                    arg_5_2,
                    arg_6_2,
                    arg_7_2,
                    arg_8_2,
                    arg_9_2,
                    arg_10_2,
                    arg_11_2,
                    arg_12_2,
                    arg_13_2,
                    arg_14_2,
                    arg_15_2,
                    arg_16_2,
                    arg_17_2,
                    arg_18_2,
                    arg_19_2,
                    arg_20_2,
                    arg_21_2,
                    arg_22_2,
                    arg_23_2,
                    arg_24_2,
                    arg_25_2,
                    arg_26_2,
                    arg_27_2,
                    arg_28_2,
                    arg_29_2,
                    arg_30_2,
                    arg_31_2,
                    arg_32_2,
                    arg_33_2,
                    arg_34_2,
                    arg_35_2,
                    arg_36_2}, this.write_violation_jyOperationCompleted, userState);
    }
    
    private void Onwrite_violation_jyOperationCompleted(object arg) {
        if ((this.write_violation_jyCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.write_violation_jyCompleted(this, new write_violation_jyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.ws.tmri.com", ResponseNamespace="http://service.ws.tmri.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("write_forceReturn", IsNullable=true)]
    public string write_force(
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_0_3, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_1_3, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_2_3, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_3_3, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_4_3, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_5_3, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_6_3, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_7_3, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_8_3, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_9_3, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_10_3, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_11_3, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_12_3, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_13_3, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_14_3, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_15_3, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_16_3, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_17_3, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_18_3, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_19_3, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_20_3, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_21_3, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_22_3, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_23_3, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_24_3, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_25_3, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_26_3, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_27_3, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_28_3, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_29_3, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_30_3, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_31_3, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_32_3, 
                long arg_33_3, 
                long arg_34_3, 
                [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_35_3) {
        object[] results = this.Invoke("write_force", new object[] {
                    arg_0_3,
                    arg_1_3,
                    arg_2_3,
                    arg_3_3,
                    arg_4_3,
                    arg_5_3,
                    arg_6_3,
                    arg_7_3,
                    arg_8_3,
                    arg_9_3,
                    arg_10_3,
                    arg_11_3,
                    arg_12_3,
                    arg_13_3,
                    arg_14_3,
                    arg_15_3,
                    arg_16_3,
                    arg_17_3,
                    arg_18_3,
                    arg_19_3,
                    arg_20_3,
                    arg_21_3,
                    arg_22_3,
                    arg_23_3,
                    arg_24_3,
                    arg_25_3,
                    arg_26_3,
                    arg_27_3,
                    arg_28_3,
                    arg_29_3,
                    arg_30_3,
                    arg_31_3,
                    arg_32_3,
                    arg_33_3,
                    arg_34_3,
                    arg_35_3});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult Beginwrite_force(
                string arg_0_3, 
                string arg_1_3, 
                string arg_2_3, 
                string arg_3_3, 
                string arg_4_3, 
                string arg_5_3, 
                string arg_6_3, 
                string arg_7_3, 
                string arg_8_3, 
                string arg_9_3, 
                string arg_10_3, 
                string arg_11_3, 
                string arg_12_3, 
                string arg_13_3, 
                string arg_14_3, 
                string arg_15_3, 
                string arg_16_3, 
                string arg_17_3, 
                string arg_18_3, 
                string arg_19_3, 
                string arg_20_3, 
                string arg_21_3, 
                string arg_22_3, 
                string arg_23_3, 
                string arg_24_3, 
                string arg_25_3, 
                string arg_26_3, 
                string arg_27_3, 
                string arg_28_3, 
                string arg_29_3, 
                string arg_30_3, 
                string arg_31_3, 
                string arg_32_3, 
                long arg_33_3, 
                long arg_34_3, 
                string arg_35_3, 
                System.AsyncCallback callback, 
                object asyncState) {
        return this.BeginInvoke("write_force", new object[] {
                    arg_0_3,
                    arg_1_3,
                    arg_2_3,
                    arg_3_3,
                    arg_4_3,
                    arg_5_3,
                    arg_6_3,
                    arg_7_3,
                    arg_8_3,
                    arg_9_3,
                    arg_10_3,
                    arg_11_3,
                    arg_12_3,
                    arg_13_3,
                    arg_14_3,
                    arg_15_3,
                    arg_16_3,
                    arg_17_3,
                    arg_18_3,
                    arg_19_3,
                    arg_20_3,
                    arg_21_3,
                    arg_22_3,
                    arg_23_3,
                    arg_24_3,
                    arg_25_3,
                    arg_26_3,
                    arg_27_3,
                    arg_28_3,
                    arg_29_3,
                    arg_30_3,
                    arg_31_3,
                    arg_32_3,
                    arg_33_3,
                    arg_34_3,
                    arg_35_3}, callback, asyncState);
    }
    
    /// <remarks/>
    public string Endwrite_force(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void write_forceAsync(
                string arg_0_3, 
                string arg_1_3, 
                string arg_2_3, 
                string arg_3_3, 
                string arg_4_3, 
                string arg_5_3, 
                string arg_6_3, 
                string arg_7_3, 
                string arg_8_3, 
                string arg_9_3, 
                string arg_10_3, 
                string arg_11_3, 
                string arg_12_3, 
                string arg_13_3, 
                string arg_14_3, 
                string arg_15_3, 
                string arg_16_3, 
                string arg_17_3, 
                string arg_18_3, 
                string arg_19_3, 
                string arg_20_3, 
                string arg_21_3, 
                string arg_22_3, 
                string arg_23_3, 
                string arg_24_3, 
                string arg_25_3, 
                string arg_26_3, 
                string arg_27_3, 
                string arg_28_3, 
                string arg_29_3, 
                string arg_30_3, 
                string arg_31_3, 
                string arg_32_3, 
                long arg_33_3, 
                long arg_34_3, 
                string arg_35_3) {
        this.write_forceAsync(arg_0_3, arg_1_3, arg_2_3, arg_3_3, arg_4_3, arg_5_3, arg_6_3, arg_7_3, arg_8_3, arg_9_3, arg_10_3, arg_11_3, arg_12_3, arg_13_3, arg_14_3, arg_15_3, arg_16_3, arg_17_3, arg_18_3, arg_19_3, arg_20_3, arg_21_3, arg_22_3, arg_23_3, arg_24_3, arg_25_3, arg_26_3, arg_27_3, arg_28_3, arg_29_3, arg_30_3, arg_31_3, arg_32_3, arg_33_3, arg_34_3, arg_35_3, null);
    }
    
    /// <remarks/>
    public void write_forceAsync(
                string arg_0_3, 
                string arg_1_3, 
                string arg_2_3, 
                string arg_3_3, 
                string arg_4_3, 
                string arg_5_3, 
                string arg_6_3, 
                string arg_7_3, 
                string arg_8_3, 
                string arg_9_3, 
                string arg_10_3, 
                string arg_11_3, 
                string arg_12_3, 
                string arg_13_3, 
                string arg_14_3, 
                string arg_15_3, 
                string arg_16_3, 
                string arg_17_3, 
                string arg_18_3, 
                string arg_19_3, 
                string arg_20_3, 
                string arg_21_3, 
                string arg_22_3, 
                string arg_23_3, 
                string arg_24_3, 
                string arg_25_3, 
                string arg_26_3, 
                string arg_27_3, 
                string arg_28_3, 
                string arg_29_3, 
                string arg_30_3, 
                string arg_31_3, 
                string arg_32_3, 
                long arg_33_3, 
                long arg_34_3, 
                string arg_35_3, 
                object userState) {
        if ((this.write_forceOperationCompleted == null)) {
            this.write_forceOperationCompleted = new System.Threading.SendOrPostCallback(this.Onwrite_forceOperationCompleted);
        }
        this.InvokeAsync("write_force", new object[] {
                    arg_0_3,
                    arg_1_3,
                    arg_2_3,
                    arg_3_3,
                    arg_4_3,
                    arg_5_3,
                    arg_6_3,
                    arg_7_3,
                    arg_8_3,
                    arg_9_3,
                    arg_10_3,
                    arg_11_3,
                    arg_12_3,
                    arg_13_3,
                    arg_14_3,
                    arg_15_3,
                    arg_16_3,
                    arg_17_3,
                    arg_18_3,
                    arg_19_3,
                    arg_20_3,
                    arg_21_3,
                    arg_22_3,
                    arg_23_3,
                    arg_24_3,
                    arg_25_3,
                    arg_26_3,
                    arg_27_3,
                    arg_28_3,
                    arg_29_3,
                    arg_30_3,
                    arg_31_3,
                    arg_32_3,
                    arg_33_3,
                    arg_34_3,
                    arg_35_3}, this.write_forceOperationCompleted, userState);
    }
    
    private void Onwrite_forceOperationCompleted(object arg) {
        if ((this.write_forceCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.write_forceCompleted(this, new write_forceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.ws.tmri.com", ResponseNamespace="http://service.ws.tmri.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("getVehViolationReturn", IsNullable=true)]
    public string getVehViolation([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_0_4, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_1_4, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_2_4) {
        object[] results = this.Invoke("getVehViolation", new object[] {
                    arg_0_4,
                    arg_1_4,
                    arg_2_4});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetVehViolation(string arg_0_4, string arg_1_4, string arg_2_4, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getVehViolation", new object[] {
                    arg_0_4,
                    arg_1_4,
                    arg_2_4}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndgetVehViolation(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void getVehViolationAsync(string arg_0_4, string arg_1_4, string arg_2_4) {
        this.getVehViolationAsync(arg_0_4, arg_1_4, arg_2_4, null);
    }
    
    /// <remarks/>
    public void getVehViolationAsync(string arg_0_4, string arg_1_4, string arg_2_4, object userState) {
        if ((this.getVehViolationOperationCompleted == null)) {
            this.getVehViolationOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetVehViolationOperationCompleted);
        }
        this.InvokeAsync("getVehViolation", new object[] {
                    arg_0_4,
                    arg_1_4,
                    arg_2_4}, this.getVehViolationOperationCompleted, userState);
    }
    
    private void OngetVehViolationOperationCompleted(object arg) {
        if ((this.getVehViolationCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getVehViolationCompleted(this, new getVehViolationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.ws.tmri.com", ResponseNamespace="http://service.ws.tmri.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("getDrvViolationReturn", IsNullable=true)]
    public string getDrvViolation([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_0_5, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_1_5, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_2_5) {
        object[] results = this.Invoke("getDrvViolation", new object[] {
                    arg_0_5,
                    arg_1_5,
                    arg_2_5});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetDrvViolation(string arg_0_5, string arg_1_5, string arg_2_5, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getDrvViolation", new object[] {
                    arg_0_5,
                    arg_1_5,
                    arg_2_5}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndgetDrvViolation(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void getDrvViolationAsync(string arg_0_5, string arg_1_5, string arg_2_5) {
        this.getDrvViolationAsync(arg_0_5, arg_1_5, arg_2_5, null);
    }
    
    /// <remarks/>
    public void getDrvViolationAsync(string arg_0_5, string arg_1_5, string arg_2_5, object userState) {
        if ((this.getDrvViolationOperationCompleted == null)) {
            this.getDrvViolationOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetDrvViolationOperationCompleted);
        }
        this.InvokeAsync("getDrvViolation", new object[] {
                    arg_0_5,
                    arg_1_5,
                    arg_2_5}, this.getDrvViolationOperationCompleted, userState);
    }
    
    private void OngetDrvViolationOperationCompleted(object arg) {
        if ((this.getDrvViolationCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getDrvViolationCompleted(this, new getDrvViolationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.ws.tmri.com", ResponseNamespace="http://service.ws.tmri.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("write_mid_jdczpReturn", IsNullable=true)]
    public string write_mid_jdczp([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_0_6, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_1_6, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_2_6, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_3_6, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_4_6, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_5_6, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_6_6, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string arg_7_6) {
        object[] results = this.Invoke("write_mid_jdczp", new object[] {
                    arg_0_6,
                    arg_1_6,
                    arg_2_6,
                    arg_3_6,
                    arg_4_6,
                    arg_5_6,
                    arg_6_6,
                    arg_7_6});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult Beginwrite_mid_jdczp(string arg_0_6, string arg_1_6, string arg_2_6, string arg_3_6, string arg_4_6, string arg_5_6, string arg_6_6, string arg_7_6, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("write_mid_jdczp", new object[] {
                    arg_0_6,
                    arg_1_6,
                    arg_2_6,
                    arg_3_6,
                    arg_4_6,
                    arg_5_6,
                    arg_6_6,
                    arg_7_6}, callback, asyncState);
    }
    
    /// <remarks/>
    public string Endwrite_mid_jdczp(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void write_mid_jdczpAsync(string arg_0_6, string arg_1_6, string arg_2_6, string arg_3_6, string arg_4_6, string arg_5_6, string arg_6_6, string arg_7_6) {
        this.write_mid_jdczpAsync(arg_0_6, arg_1_6, arg_2_6, arg_3_6, arg_4_6, arg_5_6, arg_6_6, arg_7_6, null);
    }
    
    /// <remarks/>
    public void write_mid_jdczpAsync(string arg_0_6, string arg_1_6, string arg_2_6, string arg_3_6, string arg_4_6, string arg_5_6, string arg_6_6, string arg_7_6, object userState) {
        if ((this.write_mid_jdczpOperationCompleted == null)) {
            this.write_mid_jdczpOperationCompleted = new System.Threading.SendOrPostCallback(this.Onwrite_mid_jdczpOperationCompleted);
        }
        this.InvokeAsync("write_mid_jdczp", new object[] {
                    arg_0_6,
                    arg_1_6,
                    arg_2_6,
                    arg_3_6,
                    arg_4_6,
                    arg_5_6,
                    arg_6_6,
                    arg_7_6}, this.write_mid_jdczpOperationCompleted, userState);
    }
    
    private void Onwrite_mid_jdczpOperationCompleted(object arg) {
        if ((this.write_mid_jdczpCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.write_mid_jdczpCompleted(this, new write_mid_jdczpCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void write_yhdzCompletedEventHandler(object sender, write_yhdzCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class write_yhdzCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal write_yhdzCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void write_surveilCompletedEventHandler(object sender, write_surveilCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class write_surveilCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal write_surveilCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void write_violation_jyCompletedEventHandler(object sender, write_violation_jyCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class write_violation_jyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal write_violation_jyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void write_forceCompletedEventHandler(object sender, write_forceCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class write_forceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal write_forceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void getVehViolationCompletedEventHandler(object sender, getVehViolationCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getVehViolationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getVehViolationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void getDrvViolationCompletedEventHandler(object sender, getDrvViolationCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getDrvViolationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getDrvViolationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void write_mid_jdczpCompletedEventHandler(object sender, write_mid_jdczpCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class write_mid_jdczpCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal write_mid_jdczpCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}
