// ETTZT598ActiveX.idl : ActiveX 控件项目的类型库源。

// 此文件将由 MIDL 编译器工具处理以
// 产生类型库(ETTZT598ActiveX.tlb)，该类型库将成为
// ETTZT598ActiveX.ocx.

#include <olectl.h>
#include <idispids.h>

[ uuid(7D7D0822-E349-4A21-8EE6-F396F283EA5F), version(1.0),
  helpfile("ETTZT598ActiveX.hlp"),
  helpstring("ETTZT598ActiveX ActiveX 控件模块"),
  control ]
library ETTZT598ActiveXLib
{
	importlib(STDOLE_TLB);

	//  CETTZT598ActiveXCtrl 的主调度接口

	[ uuid(6385D7D9-75CC-4D58-8987-47A96A6ACFBF),
	  helpstring("ETTZT598ActiveX Control 的调度接口")]
	dispinterface _DETTZT598ActiveX
	{
		properties:
			[id(1) , helpstring("属性 Message")] BSTR Message;
			[id(7) , helpstring("属性 IsInputOver")] SHORT IsInputOver;

	methods:
		[id(2), helpstring("方法LoadDll")] SHORT LoadDll(void);
		[id(3), helpstring("方法DestroyDll")] SHORT DestroyDll(void);
	
		[id(5), helpstring("方法CloseDeviceEx")] SHORT CloseDeviceEx(void);
		[id(6), helpstring("方法OpenDeviceEx")] SHORT OpenDeviceEx(SHORT port);
		[id(8), helpstring("方法PinLoadCardNoEx")] SHORT PinLoadCardNoEx(BSTR pan);
		[id(9), helpstring("方法ActivWorkPinEx")] SHORT ActivWorkPinEx(SHORT masterKeyIndex, SHORT workKeyIndex);
		[id(10), helpstring("方法OpenKeyVoicEx")] SHORT OpenKeyVoicEx(SHORT param);
		[id(11), helpstring("方法PinStartAddEx")] SHORT PinStartAddEx(SHORT len, SHORT pinMode, SHORT timeout);
		[id(12), helpstring("方法PinReadPinEx")] SHORT PinReadPinEx(void);
		[id(13), helpstring("方法PinReportPressedEx")] SHORT PinReportPressedEx(void);
		[id(14), helpstring("方法GetUserPin")] SHORT GetUserPin(SHORT peaMode);
	};

	//  CETTZT598ActiveXCtrl 的事件调度接口

	[ uuid(CF16CA5E-C839-49D9-95E4-8FF372445C6C),
	  helpstring("ETTZT598ActiveX Control 的事件接口") ]
	dispinterface _DETTZT598ActiveXEvents
	{
		properties:
			//  事件接口没有任何属性

		methods:
	};

	//  CETTZT598ActiveXCtrl 的类信息

	[ uuid(233B327E-114D-4AFF-8F70-427BCA747D2C),
	  helpstring("ETTZT598ActiveX Control"), control ]
	coclass ETTZT598ActiveX
	{
		[default] dispinterface _DETTZT598ActiveX;
		[default, source] dispinterface _DETTZT598ActiveXEvents;
	};

};
