using System;
using System.Collections.Generic;
using System.Text;

namespace FT.Commons.SkinProcessor
{
    public enum SkinType
    {
        Calmness,
        CalmnessColor1,
        CalmnessColor2,
        DeepCyan,
        DeepGreen,
        DeepOrange,
        DiamondBlue,
        DiamondGreen,
        Eighteen,
        EighteenColor1,
        EighteenColor2,
        Emerald,
        EmeraldColor1,
        EmeraldColor2,
        EmeraldColor3,
        GlassBrown,
        GlassGreen,
        GlassOrange,
        Longhorn,
        MacOS,
        Midsummer,
        MidsummerColor1,
        MidsummerColor2,
        MidsummerColor3,
        MP10,
        MSN,
        OneBlue,
        OneCyan,
        OneGreen,
        OneOrange,
        Page,
        PageColor1,
        PageColor2,
        RealOne,
        Silver,
        SilverColor1,
        SilverColor2,
        SportsBlack,
        SportsBlue,
        SportsCyan,
        SportsGreen,
        SportsOrange,
        StellBlack,
        StellBlue,
        Vista1,
        Vista1Green,
        Vista2Color1,
        Vista2Color2,
        Vista2Color3,
        Vista2Color4,
        Vista2Color5,
        Vista2Color6,
        Vista2Color7,
        Warm,
        WarmColor1,
        WarmColor2,
        WarmColor3,
        Wave,
        WaveColor1,
        WaveColor2,
        XPBlue,
        XPGreen,
        XPOrange,
        XPSilver,

    }
}
