// ETTPrintActiveX.idl : ActiveX 控件项目的类型库源。

// 此文件将由 MIDL 编译器工具处理以
// 产生类型库(ETTPrintActiveX.tlb)，该类型库将成为
// ETTPrintActiveX.ocx.

#include <olectl.h>
#include <idispids.h>

[ uuid(29D07778-0ECD-40A6-A799-5B9ACEBD1039), version(1.0),
  helpfile("ETTPrintActiveX.hlp"),
  helpstring("ETTPrintActiveX ActiveX 控件模块"),
  control ]
library ETTPrintActiveXLib
{
	importlib(STDOLE_TLB);

	//  CETTPrintActiveXCtrl 的主调度接口

	[ uuid(A94C9160-7DD0-4C29-A470-1B218E388B0C),
	  helpstring("ETTPrintActiveX Control 的调度接口")]
	dispinterface _DETTPrintActiveX
	{
		properties:
		methods:
	};

	//  CETTPrintActiveXCtrl 的事件调度接口

	[ uuid(3F019042-B4D1-4BA1-AF88-74B8B56172DF),
	  helpstring("ETTPrintActiveX Control 的事件接口") ]
	dispinterface _DETTPrintActiveXEvents
	{
		properties:
			//  事件接口没有任何属性

		methods:
	};

	//  CETTPrintActiveXCtrl 的类信息

	[ uuid(07F2485D-2A40-44B2-9000-04F92EB8F96A),
	  helpstring("ETTPrintActiveX Control"), control ]
	coclass ETTPrintActiveX
	{
		[default] dispinterface _DETTPrintActiveX;
		[default, source] dispinterface _DETTPrintActiveXEvents;
	};

};
