// IDCardActiveX.idl : ActiveX 控件项目的类型库源。

// 此文件将由 MIDL 编译器工具处理以
// 产生类型库(IDCardActiveX.tlb)，该类型库将成为
// IDCardActiveX.ocx.

#include <olectl.h>
#include <idispids.h>

[ uuid(5D8BBCC4-5AF8-4A1E-88E5-213CD0685ECC), version(1.0),
  helpfile("IDCardActiveX.hlp"),
  helpstring("IDCardActiveX ActiveX 控件模块"),
  control ]
library IDCardActiveXLib
{
	importlib(STDOLE_TLB);

	//  CIDCardActiveXCtrl 的主调度接口

	[ uuid(CE963D6C-DA9E-4E6F-AEAC-7F27F1248DE1),
	  helpstring("IDCardActiveX Control 的调度接口")]
	dispinterface _DIDCardActiveX
	{
		properties:
		methods:
	};

	//  CIDCardActiveXCtrl 的事件调度接口

	[ uuid(F356B5E6-5D6A-4691-A52C-87B523F60173),
	  helpstring("IDCardActiveX Control 的事件接口") ]
	dispinterface _DIDCardActiveXEvents
	{
		properties:
			//  事件接口没有任何属性

		methods:
	};

	//  CIDCardActiveXCtrl 的类信息

	[ uuid(FD63286F-7A4F-4C01-9605-2163C1ED1190),
	  helpstring("IDCardActiveX Control"), control ]
	coclass IDCardActiveX
	{
		[default] dispinterface _DIDCardActiveX;
		[default, source] dispinterface _DIDCardActiveXEvents;
	};

};
